// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsmOaIz9WJIfNcsmNhLUaZkfI7REmE71I',
    appId: '1:115069694681:web:ece6dea045c5a133e044c8',
    messagingSenderId: '115069694681',
    projectId: 'flutter-diagonal',
    authDomain: 'flutter-diagonal.firebaseapp.com',
    storageBucket: 'flutter-diagonal.firebasestorage.app',
    measurementId: 'G-PXXSSH7BJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRaNP9gZAZtd_LjbaeORmNI38A-kdmQHk',
    appId: '1:115069694681:android:043627383e29a60fe044c8',
    messagingSenderId: '115069694681',
    projectId: 'flutter-diagonal',
    storageBucket: 'flutter-diagonal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ32xdTbrXKbc9ShsNBCs6GcNj4Arh5Tk',
    appId: '1:115069694681:ios:59483658d3c2d280e044c8',
    messagingSenderId: '115069694681',
    projectId: 'flutter-diagonal',
    storageBucket: 'flutter-diagonal.firebasestorage.app',
    iosBundleId: 'com.example.ravintolaDiagonal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ32xdTbrXKbc9ShsNBCs6GcNj4Arh5Tk',
    appId: '1:115069694681:ios:59483658d3c2d280e044c8',
    messagingSenderId: '115069694681',
    projectId: 'flutter-diagonal',
    storageBucket: 'flutter-diagonal.firebasestorage.app',
    iosBundleId: 'com.example.ravintolaDiagonal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsmOaIz9WJIfNcsmNhLUaZkfI7REmE71I',
    appId: '1:115069694681:web:909675a53f4ba572e044c8',
    messagingSenderId: '115069694681',
    projectId: 'flutter-diagonal',
    authDomain: 'flutter-diagonal.firebaseapp.com',
    storageBucket: 'flutter-diagonal.firebasestorage.app',
    measurementId: 'G-YHPZW1VZ4Q',
  );
}
